# Generated by Django 3.2.5 on 2022-10-17 16:37

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orgstruktur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_orgstruktur', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='Workprogramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_workprogramme', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hp', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('ig', models.CharField(max_length=40, null=True)),
                ('alamat', models.TextField(blank=True)),
            ],
        ),
    ]
