# Generated by Django 3.2.5 on 2022-10-20 18:51

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProgrammeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_workprogramme', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath)),
            ],
        ),
    ]
