# Generated by Django 3.2.5 on 2022-10-14 23:17

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=100)),
                ('jenis_file', models.CharField(max_length=10)),
                ('ukuran_file', models.CharField(max_length=10)),
                ('file_download', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath)),
            ],
        ),
    ]
