# Generated by Django 3.2.5 on 2022-10-18 16:16

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visimisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_visimisi', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_visimisi)),
            ],
        ),
        migrations.AlterField(
            model_name='workprogramme',
            name='file_workprogramme',
            field=models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_workprogramme),
        ),
    ]
