# Generated by Django 3.2.5 on 2022-10-18 17:14

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='divisippi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_divisippi', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_divisi_ppi)),
            ],
        ),
        migrations.AlterField(
            model_name='orgstruktur',
            name='file_orgstruktur',
            field=models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_orgstruktur),
        ),
    ]
