# Generated by Django 3.2.5 on 2022-10-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloads',
            name='jenis_file',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='nama_file',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='ukuran_file',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
