# Generated by Django 3.2.5 on 2022-10-20 18:02

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgstrukturModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgstruktur_image', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath)),
            ],
        ),
        migrations.DeleteModel(
            name='orgstruktur',
        ),
    ]
