# Generated by Django 3.2.5 on 2022-10-19 13:22

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_umkt_press'),
    ]

    operations = [
        migrations.CreateModel(
            name='elearning_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(blank=True)),
                ('member_image', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_elearning_support)),
            ],
        ),
    ]
