# Generated by Django 3.2.5 on 2022-10-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20221017_2141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Downloads',
            new_name='DownloadContent',
        ),
    ]
