# Generated by Django 3.2.8 on 2022-10-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_journal_serving'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='journal_serving',
            new_name='JournalServingModel',
        ),
    ]
