# Generated by Django 3.2.5 on 2022-10-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20221018_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visimisi',
            name='file_visimisi',
        ),
        migrations.AddField(
            model_name='visimisi',
            name='misi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visimisi',
            name='visi',
            field=models.TextField(blank=True),
        ),
    ]
