# Generated by Django 3.2.5 on 2022-10-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20221018_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisippi',
            old_name='file_divisippi',
            new_name='member_image',
        ),
        migrations.AddField(
            model_name='divisippi',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
