# Generated by Django 3.2.8 on 2022-10-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_umkt_press'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='umkt_press',
            new_name='UmktPress',
        ),
        migrations.RenameField(
            model_name='umktpress',
            old_name='member_image',
            new_name='umktpress_flowservice',
        ),
        migrations.RenameField(
            model_name='umktpress',
            old_name='overview',
            new_name='umktpress_overview',
        ),
    ]
