# Generated by Django 3.2.8 on 2022-10-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_elearning_support'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='elearning_support',
            new_name='ElearningSupportModel',
        ),
    ]
