# Generated by Django 3.2.5 on 2022-10-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_auto_20221018_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=50, null=True)),
                ('Judul_Artikel', models.CharField(max_length=100, null=True)),
                ('Tahun', models.CharField(max_length=4, null=True)),
                ('Link', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
