# Generated by Django 3.2.8 on 2022-10-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='member_image',
            new_name='event_image',
        ),
    ]
