# Generated by Django 3.2.5 on 2022-10-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_auto_20221018_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisippi',
            old_name='member_image',
            new_name='flowservice_divisippi',
        ),
        migrations.RenameField(
            model_name='divisippi',
            old_name='overview',
            new_name='overview_divisippi',
        ),
    ]
