# Generated by Django 3.2.5 on 2022-10-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_divisielearning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisielearning',
            old_name='member_image',
            new_name='flowservice_divisielearning',
        ),
        migrations.RenameField(
            model_name='divisielearning',
            old_name='overview',
            new_name='overview_divisielearning',
        ),
    ]
