# Generated by Django 3.2.8 on 2022-10-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_rename_member_image_event_event_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='EventModel',
        ),
    ]
