# Generated by Django 3.2.8 on 2022-10-20 16:57

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_rename_elearning_support_elearningsupportmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElearningSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elearningsupport_flowservice', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_elearning_support)),
                ('elearningsupport_overview', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ElearningSupportModel',
        ),
    ]
