# Generated by Django 3.2.5 on 2022-10-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_journals'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program_Studi', models.CharField(max_length=50, null=True)),
                ('Nama', models.CharField(max_length=50, null=True)),
                ('Judul_Buku', models.CharField(max_length=100, null=True)),
                ('Tahap_Luaran_10', models.BooleanField(default=False)),
                ('Tahap_Luaran_40', models.BooleanField(default=False)),
                ('Tahap_Luaran_80', models.BooleanField(default=False)),
                ('Reviewer', models.CharField(max_length=100, null=True)),
                ('Tahun', models.CharField(max_length=100, null=True)),
                ('Link', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
