# Generated by Django 3.2.5 on 2022-10-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_articletranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletranslation',
            old_name='member_image',
            new_name='flowservice_articletranslation',
        ),
        migrations.RenameField(
            model_name='articletranslation',
            old_name='overview',
            new_name='overview_articletranslation',
        ),
    ]
