# Generated by Django 3.2.5 on 2022-10-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20221020_1802'),
        ('landingpage', '0004_auto_20221020_1725'),
    ]

    operations = [
    ]
