# Generated by Django 3.2.5 on 2022-10-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_rename_event_eventmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='ContactModel',
        ),
    ]
