# Generated by Django 3.2.5 on 2022-10-19 16:48

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_sipena'),
    ]

    operations = [
        migrations.CreateModel(
            name='journalresearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_image', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_journal_research)),
                ('overview', models.TextField(blank=True)),
            ],
        ),
    ]
