# Generated by Django 3.2.8 on 2022-10-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_auto_20221020_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElearningSupportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elearningsupport_overview', models.TextField(blank=True)),
            ],
        ),
    ]
