# Generated by Django 3.2.5 on 2022-10-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_sipena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sipena',
            old_name='member_image',
            new_name='flowservice_sipena',
        ),
        migrations.RenameField(
            model_name='sipena',
            old_name='overview',
            new_name='overview_sipena',
        ),
    ]
