# Generated by Django 3.2.5 on 2022-10-21 17:08

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_merge_0002_auto_20221020_1802_0004_auto_20221020_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='orgstruktur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_orgstruktur', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_orgstruktur)),
            ],
        ),
        migrations.AddField(
            model_name='divisippi',
            name='test_aja',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
