# Generated by Django 3.2.5 on 2022-10-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_auto_20221021_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisippi',
            name='test_aja',
        ),
    ]
