# Generated by Django 3.2.8 on 2022-10-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_elearningsupportmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElearningSupportModel',
        ),
    ]
