# Generated by Django 3.2.5 on 2022-10-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20221020_1802'),
        ('landingpage', '0006_auto_20221020_1533'),
    ]

    operations = [
    ]
