# Generated by Django 3.2.5 on 2022-10-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_rename_contact_contactmodel'),
        ('landingpage', '0007_merge_0002_auto_20221020_1802_0006_auto_20221020_1533'),
    ]

    operations = [
    ]
