# Generated by Django 3.2.5 on 2022-10-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_newspaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewspaperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dosen', models.CharField(max_length=50, null=True)),
                ('judul_artikel', models.CharField(max_length=100, null=True)),
                ('tahun', models.CharField(max_length=4, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='newspaper',
        ),
    ]
