# Generated by Django 3.2.5 on 2022-10-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_merge_20221028_2154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='journal_serving',
            new_name='Journal_ServingModel',
        ),
    ]
