# Generated by Django 3.2.5 on 2022-10-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_auto_20221024_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspapermodel',
            name='fakultas',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newspapermodel',
            name='nidn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newspapermodel',
            name='prodi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
