# Generated by Django 3.2.5 on 2022-10-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_auto_20221024_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspapermodel',
            old_name='prodi',
            new_name='program_studi',
        ),
    ]
