# Generated by Django 3.2.5 on 2022-10-29 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_auto_20221024_1511'),
        ('landingpage', '0009_rename_journal_serving_journal_servingmodel'),
    ]

    operations = [
    ]
