# Generated by Django 3.2.5 on 2022-11-03 10:50

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0010_merge_20221029_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowservice_divisippi', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_divisi_ppi)),
                ('overview_divisippi', models.TextField(blank=True)),
            ],
        ),
    ]
