# Generated by Django 3.2.5 on 2022-11-03 11:19

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0011_ppimodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElearningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowservice_divisielearning', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_divisi_elearning)),
                ('overview_divisielearning', models.TextField(blank=True)),
            ],
        ),
    ]
