# Generated by Django 3.2.5 on 2022-11-03 14:25

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0013_articletranslationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipenaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowservice_sipena', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_service)),
                ('overview_sipena', models.TextField(blank=True)),
            ],
        ),
    ]
