# Generated by Django 3.2.5 on 2022-11-04 09:27

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0015_umktpressmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowservice_service', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_service)),
                ('overview_service', models.TextField(blank=True)),
            ],
        ),
    ]
