# Generated by Django 3.2.5 on 2022-11-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0016_servicemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleTranslationModel',
        ),
        migrations.DeleteModel(
            name='SipenaModel',
        ),
        migrations.DeleteModel(
            name='UmktPressModel',
        ),
    ]
