# Generated by Django 3.2.5 on 2022-11-07 13:30

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0017_auto_20221104_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_divisi', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_divisi)),
                ('overview_divisi', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ElearningModel',
        ),
        migrations.DeleteModel(
            name='PPIModel',
        ),
    ]
