# Generated by Django 3.2.5 on 2022-11-07 18:18

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0018_auto_20221107_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalUmktModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_jurnal', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_journal_umkt)),
                ('judul_jurnal', models.CharField(blank=True, max_length=50)),
                ('issn', models.CharField(blank=True, max_length=20)),
                ('publication', models.CharField(blank=True, max_length=50)),
                ('index', models.TextField(blank=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('link_view_jurnal', models.CharField(blank=True, max_length=100)),
                ('link_current_issue', models.CharField(blank=True, max_length=100)),
                ('link_online_submission', models.CharField(blank=True, max_length=100)),
                ('link_download_template', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Journal_ServingModel',
        ),
    ]
