# Generated by Django 3.2.5 on 2022-11-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0019_auto_20221107_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalumktmodel',
            name='jenis_journal',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
