# Generated by Django 3.2.5 on 2022-11-09 15:05

from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0020_journalumktmodel_jenis_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=100, null=True)),
                ('jenis_file', models.CharField(max_length=10, null=True)),
                ('ukuran_file', models.CharField(max_length=10, null=True)),
                ('file_download', models.FileField(blank=True, null=True, upload_to=landingpage.models.filepath_downloads)),
            ],
        ),
    ]
