# Generated by Django 3.2.5 on 2022-11-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0021_downloadcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadcontent',
            name='jenis_file',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
