# Generated by Django 3.2.5 on 2023-02-16 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0022_alter_downloadcontent_jenis_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakultasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_fakultas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prodi', models.TextField(blank=True)),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.fakultasmodel')),
            ],
        ),
    ]
