# Generated by Django 3.2.5 on 2023-02-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0023_fakultasmodel_prodimodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.TextField(blank=True, max_length=30)),
                ('nama', models.TextField(blank=True, max_length=100)),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.fakultasmodel')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.prodimodel')),
            ],
        ),
    ]
