# Generated by Django 3.2.5 on 2023-02-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0024_alter_newsmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='kategori',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
