# Generated by Django 3.2.5 on 2023-02-16 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0024_dosenmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosenmodel',
            name='fakultas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.fakultasmodel'),
        ),
    ]
