# Generated by Django 3.2.5 on 2023-02-16 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0025_alter_dosenmodel_fakultas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahasiswaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.TextField(blank=True, max_length=30)),
                ('angkatan', models.TextField(blank=True, max_length=5)),
                ('nama', models.TextField(blank=True, max_length=100)),
                ('fakultas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.fakultasmodel')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.prodimodel')),
            ],
        ),
    ]
