# Generated by Django 3.2.5 on 2023-02-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0026_mahasiswamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriIndexModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(blank=True)),
            ],
        ),
    ]
