# Generated by Django 3.2.5 on 2023-02-20 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0027_kategoriindexmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenelitianDosenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField(blank=True, max_length=150)),
                ('tahun', models.TextField(blank=True, max_length=4)),
                ('penyedia_jurnal', models.TextField(blank=True, max_length=100)),
                ('asal_pendanaan', models.TextField(blank=True, max_length=100)),
                ('total_pendanaan', models.TextField(blank=True, max_length=50)),
                ('link_publikasi', models.TextField(blank=True, max_length=200)),
                ('fakultas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.fakultasmodel')),
                ('kategori_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.kategoriindexmodel')),
                ('ketua_peneliti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.dosenmodel')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.prodimodel')),
            ],
        ),
    ]
