# Generated by Django 3.2.5 on 2023-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0028_penelitiandosenmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penelitiandosenmodel',
            name='total_pendanaan',
            field=models.IntegerField(blank=True),
        ),
    ]
