# Generated by Django 3.2.5 on 2023-02-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0029_alter_penelitiandosenmodel_total_pendanaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='penelitiandosenmodel',
            name='anggota_peneliti',
            field=models.ManyToManyField(related_name='anggota_peneliti', to='landingpage.DosenModel'),
        ),
    ]
