# Generated by Django 3.2.5 on 2023-02-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0030_penelitiandosenmodel_anggota_peneliti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penelitiandosenmodel',
            name='anggota_peneliti',
        ),
        migrations.CreateModel(
            name='AnggotaPenelitiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.dosenmodel')),
                ('fakultas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.fakultasmodel')),
                ('penelitian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.penelitiandosenmodel')),
                ('prodi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.prodimodel')),
            ],
        ),
    ]
