# Generated by Django 3.2.5 on 2023-02-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0031_auto_20230222_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnggotaPenelitiModel',
            new_name='AnggotaPenelitiDosenModel',
        ),
        migrations.RenameField(
            model_name='anggotapenelitidosenmodel',
            old_name='anggota',
            new_name='anggota_dosen',
        ),
        migrations.AlterField(
            model_name='mahasiswamodel',
            name='nim',
            field=models.TextField(blank=True, max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='AnggotaPenelitiMahasiswaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anggota_mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.mahasiswamodel')),
                ('fakultas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.fakultasmodel')),
                ('penelitian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.penelitiandosenmodel')),
                ('prodi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.prodimodel')),
            ],
        ),
    ]
