# Generated by Django 3.2.5 on 2023-02-23 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0032_auto_20230222_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnggotaPenelitiDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peran', models.CharField(blank=True, max_length=50)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.dosenmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Penelitian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('tanggal_publikasi', models.DateField(default=django.utils.timezone.now)),
                ('anggota_dosen', models.ManyToManyField(through='landingpage.AnggotaPenelitiDosen', to='landingpage.DosenModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='anggotapenelitimahasiswamodel',
            name='anggota_mahasiswa',
        ),
        migrations.RemoveField(
            model_name='anggotapenelitimahasiswamodel',
            name='fakultas',
        ),
        migrations.RemoveField(
            model_name='anggotapenelitimahasiswamodel',
            name='penelitian',
        ),
        migrations.RemoveField(
            model_name='anggotapenelitimahasiswamodel',
            name='prodi',
        ),
        migrations.RemoveField(
            model_name='penelitiandosenmodel',
            name='fakultas',
        ),
        migrations.RemoveField(
            model_name='penelitiandosenmodel',
            name='kategori_index',
        ),
        migrations.RemoveField(
            model_name='penelitiandosenmodel',
            name='ketua_peneliti',
        ),
        migrations.RemoveField(
            model_name='penelitiandosenmodel',
            name='prodi',
        ),
        migrations.DeleteModel(
            name='AnggotaPenelitiDosenModel',
        ),
        migrations.DeleteModel(
            name='AnggotaPenelitiMahasiswaModel',
        ),
        migrations.DeleteModel(
            name='PenelitianDosenModel',
        ),
        migrations.AddField(
            model_name='anggotapenelitidosen',
            name='penelitian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.penelitian'),
        ),
    ]
