# Generated by Django 3.2.5 on 2023-02-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0033_auto_20230223_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnggotaPenelitiDosenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anggota_dosen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.dosenmodel')),
                ('fakultas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.fakultasmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AnggotaPenelitiMahasiswaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anggota_mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.mahasiswamodel')),
                ('fakultas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.fakultasmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PenelitianDosenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField(blank=True, max_length=150)),
                ('tahun', models.TextField(blank=True, max_length=4)),
                ('penyedia_jurnal', models.TextField(blank=True, max_length=100)),
                ('asal_pendanaan', models.TextField(blank=True, max_length=100)),
                ('total_pendanaan', models.IntegerField(blank=True)),
                ('link_publikasi', models.TextField(blank=True, max_length=200)),
                ('fakultas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.fakultasmodel')),
                ('kategori_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.kategoriindexmodel')),
                ('ketua_peneliti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.dosenmodel')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.prodimodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='penelitian',
            name='anggota_dosen',
        ),
        migrations.DeleteModel(
            name='AnggotaPenelitiDosen',
        ),
        migrations.DeleteModel(
            name='Penelitian',
        ),
        migrations.AddField(
            model_name='anggotapenelitimahasiswamodel',
            name='penelitian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.penelitiandosenmodel'),
        ),
        migrations.AddField(
            model_name='anggotapenelitimahasiswamodel',
            name='prodi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.prodimodel'),
        ),
        migrations.AddField(
            model_name='anggotapenelitidosenmodel',
            name='penelitian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.penelitiandosenmodel'),
        ),
        migrations.AddField(
            model_name='anggotapenelitidosenmodel',
            name='prodi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.prodimodel'),
        ),
    ]
