# Generated by Django 3.2.5 on 2023-02-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0034_auto_20230223_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='penelitiandosenmodel',
            name='salt',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='penelitiandosenmodel',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
