# Generated by Django 3.2.5 on 2023-02-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0035_auto_20230224_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggotapenelitidosenmodel',
            name='salt',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='anggotapenelitimahasiswamodel',
            name='salt',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='anggotapenelitidosenmodel',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='anggotapenelitimahasiswamodel',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
