# Generated by Django 3.2.5 on 2023-02-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0036_auto_20230225_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggotapenelitidosenmodel',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='anggotapenelitimahasiswamodel',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='penelitiandosenmodel',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
