# Generated by Django 3.2.5 on 2023-02-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0039_anggotapengabdiandosenmodel_anggotapengabdianmahasiswamodel_pengabdiandosenmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anggotapengabdiandosenmodel',
            old_name='penelitian',
            new_name='pengabdian',
        ),
        migrations.RenameField(
            model_name='anggotapengabdianmahasiswamodel',
            old_name='penelitian',
            new_name='pengabdian',
        ),
    ]
