# Generated by Django 3.2.5 on 2023-02-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0040_auto_20230225_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidasiOpl',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=64, null=True)),
                ('kode_matkul', models.CharField(max_length=10, unique=True)),
                ('nama_matkul', models.CharField(max_length=50)),
                ('link_matkul', models.CharField(max_length=50)),
                ('ch1', models.FloatField(default=0, max_length=2)),
                ('ch2', models.FloatField(default=0, max_length=2)),
                ('ch3', models.FloatField(default=0, max_length=2)),
                ('ch4', models.FloatField(default=0, max_length=2)),
                ('ch5', models.FloatField(default=0, max_length=2)),
                ('ch6', models.FloatField(default=0, max_length=2)),
                ('ch7', models.FloatField(default=0, max_length=2)),
                ('ch8', models.FloatField(default=0, max_length=2)),
                ('ch9', models.FloatField(default=0, max_length=2)),
                ('ch10', models.FloatField(default=0, max_length=2)),
                ('ch11', models.FloatField(default=0, max_length=2)),
                ('ch12', models.FloatField(default=0, max_length=2)),
                ('ch13', models.FloatField(default=0, max_length=2)),
                ('ch14', models.FloatField(default=0, max_length=2)),
                ('progres', models.FloatField(default=0, max_length=4)),
                ('keterangan', models.CharField(default='-', max_length=100)),
                ('status_haki', models.CharField(default=0, max_length=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('fakultas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.fakultasmodel')),
                ('pemilik_cource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.dosenmodel')),
                ('prodi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.prodimodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
