# Generated by Django 3.2.5 on 2023-02-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0041_validasiopl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validasiopl',
            old_name='pemilik_cource',
            new_name='pemilik_course',
        ),
    ]
