# Generated by Django 3.2.5 on 2023-02-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0042_rename_pemilik_cource_validasiopl_pemilik_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validasiopl',
            name='link_matkul',
            field=models.CharField(max_length=255),
        ),
    ]
