# Generated by Django 3.2.5 on 2023-03-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0023_newsmodel'),
        ('landingpage', '0044_teamteachingmodel'),
    ]

    operations = [
    ]
